parameters:

    #
    # Form Types
    #
    elcodi.admin.product.form_type.product.class: Elcodi\Admin\ProductBundle\Form\Type\ProductType
    elcodi.admin.product.form_type.product_variant.class: Elcodi\Admin\ProductBundle\Form\Type\VariantType
    elcodi.admin.product.form_type.category.class: Elcodi\Admin\ProductBundle\Form\Type\CategoryType
    elcodi.admin.product.form_type.manufacturer.class: Elcodi\Admin\ProductBundle\Form\Type\ManufacturerType

    #
    # Event listeners
    #
    elcodi.admin.product.event_listener.new_category_position.class: Elcodi\Admin\ProductBundle\EventListener\NewCategoryPositionEventListener

    #
    # Services
    #
    elcodi.admin.product.services.category_sorter.class: Elcodi\Admin\ProductBundle\Services\CategorySorter
