services:

    #
    # Services
    #
    elcodi.store.geo.form.location_selector_builder:
        class: %elcodi.store.geo.form.location_selector_builder.class%
        arguments:
            location_provider: @elcodi.location_provider
